trigger:
- master
- development

steps:
- powershell: |
    Write-Verbose -Verbose "##vso[build.updatebuildnumber]$(BuildVersion)"
  displayName: Update Build Number
            
- checkout: self
  displayName: 'Download Files From Repository'

- task: DeleteFiles@1
  displayName: 'Remove Pipeline File'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '*.yml'
    RemoveDotFiles: true

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(BuildVersion).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  displayName: Publish txt file
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'Readme.txt'
    publishLocation: 'FilePath'
    TargetPath: '$(DropLocation)'

- task: PublishBuildArtifacts@1
  displayName: Publish zip file
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: '$(Build.BuildId).zip'
    publishLocation: 'FilePath'
    TargetPath: '$(DropLocation)'

