pool:
  vmImage: ubuntu-latest
  
# variables:
# - name: User
#   value: RamkrishnaKakani
# - name: Organization
#   value: RamkrishnaKakani
# - name: Repo_Name
#   value: DropZip

steps:
  - task: DotNetCoreCLI@2  
    displayName: Install NBGV tool
    inputs:
      command: custom
      custom: tool
      arguments: install --tool-path . nbgv
      
  - script: nbgv cloud
    enabled: true
    displayName: Set Version    
    
  - script: echo "Ramkrishna"
    enabled: true
    displayName: Get Version     
    
# - task: PowerShell@2
#   displayName: 'Delete Branch'
#   inputs:
#     targetType: 'inline'
#     script: |
#       Write-Host "Printing Build Commit SHA : "
#       $SHA = "$(Build.SourceVersion)"
#       Write-Host $SHA
#       Write-Host "------------------------------------------"

#       $commit = curl -X GET -u $(User):$(GitToken) https://api.github.com/repos/$(Organization)/$(Repo_Name)/commits/$SHA/pulls | ConvertFrom-Json
#       $branchURL = $commit.url
#       Write-Host "Branch URL to be Deleted : "
#       Write-Host $branchURL
#       Write-Host "------------------------------------------"

#       $prinfo   = curl -X GET -u $(User):$(GitToken) $branchURL | ConvertFrom-Json
#       $branchtobedeleted = $prinfo.head.ref    
#       Write-Host "Branch to be Deleted : " 
#       Write-Host $branchtobedeleted
#       Write-Host "------------------------------------------"

#       curl -s -X DELETE -u $(User):$(GitToken) https://api.github.com/repos/$(Organization)/$(Repo_Name)/git/refs/heads/$branchtobedeleted
#       Write-Host "Branch Deleted..!" 
#       Write-Host "------------------------------------------"
#   condition: and(succeeded(), eq(variables['Build.Reason'], 'IndividualCI'))    
