trigger:
- master
- development

variables:
  PatchVersion : $[counter(variables['PatchVersion'],4)]
  BuildVersion: $(MajorVersion).$(MinorVersion).$(PatchVersion)

steps:
- powershell: |
    Write-Verbose -Verbose "##vso[build.updatebuildnumber]$(BuildVersion)"
  displayName: Update Build Number
            
- checkout: self
  displayName: 'Download Files From Repository'

- task: CopyFiles@2
  displayName: 'Copy Readme.txt File '
  inputs:
    SourceFolder: '$(build.sourcesdirectory)'
    Contents: 'Readme.txt'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: DeleteFiles@1
  displayName: 'Remove Pipeline File'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '*.yml'
    RemoveDotFiles: true

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(BuildVersion).zip'
    replaceExistingArchive: true

- task: CopyFiles@2
  displayName: 'Droping Zip & Txt File at Dropping Location'
  inputs:
    SourceFolder: '$(build.artifactstagingdirectory)'
    Contents: '**'
    TargetFolder: '$(DropLocation)'

- task: PublishBuildArtifacts@1
  enabled: false
  displayName: Publish txt file
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'Readme.txt'
    publishLocation: 'FilePath'
    TargetPath: '$(DropLocation)'

- task: PublishBuildArtifacts@1
  enabled: false
  displayName: Publish zip file
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    publishLocation: 'FilePath'
    TargetPath: '$(DropLocation)'

