trigger:
- none

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'C:\Users\R888066\Desktop\automapper.11.0.1.nupkg'
    ArtifactName: 'drop'
    publishLocation: 'Container'