name: BlockMergeOnProtectedBranch

on:  
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: BlockMerge
        shell: pwsh
        run: |
          ./BlockMergerOnProtectedBranch.ps1 -Token ${{ secrets.GPAT_TOKEN }} -ownerName "RamkrishnaKakani" -repoName "DropZip" -protectedBranch "master" -pullNumber ${{ github.event.number }}
          echo "PR Number:"
          echo ${{ github.event.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GPAT_TOKEN }}  
          
      - name: Run a one-line script
        run: echo Hello, world!
